# Generated by Django 4.2.27 on 2025-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
