# Generated by Django 4.2.27 on 2025-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='subject',
            field=models.CharField(blank=True, default='Contact Form Submission', max_length=200),
        ),
    ]
